### PR TITLE
Enhance example providing prometheus endpoint

### PR DESCRIPTION
**Pull request by sbilello**
This PR highlights a few TODOs if we want to expose a prometheus endpoint with the graphql metrics.
The module `com.netflix.graphql.dgs:graphql-dgs-spring-boot-micrometer` needs a dependency update for micrometer but this is a workaround that makes it work.
You can feel free to discard the PR or upgrade the corresponding dependency and fix the issue.
Thanks! @berngp for https://github.com/Netflix/dgs-framework/pull/242 and @paulbakker for this great example!

### CODE REVIEW

**Comment by berngp** [comment]
@sbilello thanks for the PR and thank you for pointing out the need to upgrade the version of micrometer. As you already might be aware the version of micrometer is defined in the Spring Boot BOM 2.3.6.RELEASE. I think in this case we can look at upgrading the DGS Framework to use Spring Boot 2.3.9.RELEASE.

I also think that adding the auto-configurations for scalars as well as an application.yml that includes the info and health endpoints makes sense. That said I have some additional questions...

1. By chance can you share additional info around the issue with micrometer 1.5.7?
2. If we upgrade the DGS Framework to use Spring Boot 2.3.9.RELEASE we will have micrometer-core 1.5.11. Would this suffice?
3. Your PR is also adding both the DGS `graphql-dgs-spring-boot-micrometer` and Micrometer's `micrometer-registry-prometheus`. I think the first makes sense but could you help me understand the latter? Not sure we want to reflect an opinion on a system that backs metrics, for example, internally we use Atlas to backup metrics.

**Comment by sbilello** [comment]
Thanks for the reply

1 & 2) The problem is given by upgrading `spring-boot-2.4.0` https://github.com/Netflix/dgs-examples-java/blob/main/build.gradle.kts#L20 that carries `micrometer-core-1.6.1` https://scans.gradle.com/s/edawrzchnz3ze/console-log#L938
you would get this exception at runtime
```
java.lang.NoSuchMethodError: io.micrometer.core.instrument.Timer$Sample.stop(Lio/micrometer/core/instrument/MeterRegistry;Lio/micrometer/core/instrument/Timer$Builder;)J
```
The proper fix should be to upgrade spring-boot so you would have a micrometer compatible version in `graphql-dgs-spring-boot-micrometer` module

3) I had to declare `micrometer-registry-prometheus` otherwise I would not have the Prometheus endpoint working.
https://micrometer.io/docs/registry/prometheus. It would be good to mention in the documentation that you did the work of creating a micrometer module ready for exposing Prometheus metrics so it might be used by others
There are a few things that can be "opinionated" but at least they belong to the CNCF umbrella and I would consider it as a standard if I don't want to buy anything from any vendor.

I am already imagining an architecture with a consul discovery mechanism plugged into a Prometheus and Grafana. It could be also inside k8s the discovery mechanism implemented but at least I cover most of the stuff that vendors sell to enterprise companies.

P.S.
If you are going to open-source the gateway and the registry please give me a heads-up. For my use case, I am leveraging this framework and thank you very much for your hard work but later on, I might need to spend time to work on the gateway and registry by myself if I have the constraint that I can not rely on any SaaS solution :)

I have also few ideas on how to cover all the [security aspects](https://leapgraph.com/graphql-api-security/) and I am already playing with [this](https://github.com/Netflix/dgs-examples-java/compare/main...sbilello:add-query-complexity#diff-6a34cfab2b2e0a7b37f6a04f99df8c679adc3f1bb63099b3e58679be6fa6aed6) to figure out how it can shield the server to process queries that could tear down the backend services.

If we had an umbrella of out-of-the-box features where the developer can focus just on designing the graph and resolvers rather than reinventing the wheel to cover all these infrastructure/security aspects would be great!

I really liked the [nodelimit](https://docs.github.com/en/graphql/overview/resource-limitations#node-limit) approach from GitHub and I believe that this could be an out-of-the-box solution ready to be implemented as well as a rate-limiter.

All items on my plate unless there are not already implemented. :)

**Comment by paulbakker** [comment]
Fix for the micrometer issue is here: https://github.com/Netflix/dgs-framework/pull/268

**Comment by sbilello** [comment]
@berngp @paulbakker I can update this PR after the dependencies have been updated without downgrading spring-boot to 2.3.9.RELEASE
Thanks!

**Comment by berngp** [comment]
Hi @sbilello, suggest you use the latest release. Could you also rebase against the latest version of the example.

I don't see a big issue on adding `micrometer-registry-prometheus` as a dependency, that said, I am hesitant we will loose the intent of _keeping_ this example as simple as possible. One thing we could consider is adding yet another example that is more lenient on expressing additional _cloud_ pattern.

I appreciate the links you posted and think that the post on _["HOW TO SECURE A GRAPHQL API (THE COMPLETE VULNERABILITY CHECKLIST)"](https://leapgraph.com/graphql-api-security/)_ by Nous Populi is really interesting. I, personally, think it could be a source of ideas that can eventually come out of the box by using additional modules, either internal or external. Thankfully Spring Boot offers a large set of features that can be used to auto-enable them as necessary. We also have a `graphql-dgs-platform-dependencies` BOM that could aid you if you decide to develop a new library.

Answering your question related to the _gateway_.
> If you are going to open-source the gateway and the registry please give me a heads-up.
*A*: The team I work in, and the one that maintains DGS, doesn't maintain the Gateway. As of now the team that owns the gateway doesn't have any short term plan to open-source it.

**Comment by sbilello** [comment]
Thanks, @berngp I am closing this PR given you might create a _cloud_ based example.

I would suggest adding some docs regarding the cloud functionalities like micrometer exporters etc... I figured it out by reading the code the presence of `graphql-dgs-spring-boot-micrometer` and that I can get Prometheus metrics out of the box.

Thanks for your work! 

Please let me know if you are going to add the autoconfiguration for scalars I am going to add that module by default :)

**Comment by berngp** [comment]
Yes, will add both metrics and extension. There are now some docs on both.

**Comment by sbilello** [comment]
Feel free to ping me if you are going to cover some of the points like the **nodelimit**. I have other aspects to cover internally but I will try to read the commits if I find something that overlaps with what I am already doing! Thanks!

**Pull request closed without merging**
