### PR TITLE
Show how to handle PageInfo without registering as Scalar

### PR DESCRIPTION
**Pull request by sbilello**
The goal of this PR is to highlight that the `PageInfoScalar` needs to be registered in order to make it work.

It can not be merged if the proper fix for registering the `Scalar` is added. 

Just to follow-up the conversation on these threads: https://github.com/Netflix/dgs-codegen/issues/141#issuecomment-853178200 and https://github.com/Netflix/dgs-framework/discussions/371#discussioncomment-847123
Thanks @srinivasankavitha

### CODE REVIEW

**Comment by srinivasankavitha** [comment]
@sbilello  - We don't technically need to set up PageInfo as a scalar to use it. This is more of a custom use case, rather than an exception. As mentioned in the discussion threads, you should be able to use PageInfo as is. So I don't think the general example needs to be updated to show that.

**Comment by sbilello** [comment]
@srinivasankavitha did you try to follow your suggestion and test it? The goal of this PR is to highlight how it can work with the current code.

**Comment by srinivasankavitha** [comment]
Ok, I think I understand the missing piece. You do need to add this to your schema for `PageInfo` to work:
```
type PageInfo {
    hasNextPage: Boolean!
    hasPreviousPage: Boolean!
    startCursor: String
    endCursor: String
}
```
This would then map to the corresponding graphql.relay.PageInfo type. This is the pattern we have used internally.
Would that work for your use case?

**Comment by sbilello** [comment]
@srinivasankavitha Thanks for pointing out the problem! I added your suggestion and now it works. Do you think that we should document this or avoid to declare the `type PageInfo` ?

**Comment by srinivasankavitha** [comment]
@sbilello  - yes, documenting this makes sense for reference, since PageInfo is a commonly used type. Please go head and close out this PR since we don't want to use this pattern for solving the PageInfo issue (You can if the developer prefers to, but there is a simpler solution anyway by declaring it as a type in the schema).

**Comment by sbilello** [comment]
Thanks, @srinivasankavitha!

**Pull request closed without merging**
